## Библиотека Numpy

#### При подготовке ноутбука использовался сайт: http://www.inp.nsk.su/~grozin/python/

---

Пакет `numpy`(НамПай) предоставляет $n$-мерные однородные массивы (все элементы одного типа); в них нельзя вставить или удалить элемент в произвольном месте. В `numpy` реализовано много операций над массивами в целом. Если задачу можно решить, произведя некоторую последовательность операций над массивами, то это будет столь же эффективно, как в `C` или `matlab` - львиная доля времени тратится в библиотечных функциях, написанных на `C`.

## Одномерные массивы

In [1]:
from numpy import (array,zeros,ones,arange,linspace,logspace,
                   float64,int64,sin,cos,pi,exp,log,sqrt,abs,
                   nan,inf,any,all,sort,hstack,vstack,hsplit,
                   delete,insert,append,eye,fromfunction,
                   trace,diag,average,std,outer,meshgrid)

Можно преобразовать список в массив.

In [2]:
a = array([3, 4, 1])
a, type(a)

(array([3, 4, 1]), numpy.ndarray)

`print` печатает массивы в удобной форме.

In [3]:
print(a)

[3 4 1]


Класс `ndarray` имеет много методов.

In [4]:
set(dir(a)) - set(dir(object))

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setitem__',
 '__setstate__',
 '__sub__',
 '__truediv__',
 '__xor

Наш массив одномерный.

In [5]:
a.ndim

1

In [6]:
print(a)

[3 4 1]


В $n$-мерном случае возвращается кортеж размеров по каждой координате.

ndarray.ndim — число осей (измерений) массива. Как уже было сказано, в мире Python число измерений часто называют рангом.

ndarray.shape — размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). 



In [7]:
a.shape

(3,)

In [8]:
len(a), a.size

(3, 3)

#### Вопрос
Как связаны элементы кортежа shape, ndim, size?

`numpy` предоставляет несколько типов для целых (`int16`, `int32`, `int64`) и чисел с плавающей точкой (`float32`, `float64`).

In [9]:
a.dtype, a.dtype.name, a.itemsize

(dtype('int64'), 'int64', 8)

Массивы - изменяемые объекты, в отличие от кортежей

In [10]:
a[1] = 3
print(a)

[3 3 1]


Массивы, разумеется, можно использовать в `for` циклах. Но при этом теряется главное преимущество `numpy` - быстродействие. Всегда, когда это возможно, лучше использовать операции над массивами как едиными целыми.

In [11]:
%%time
for i in a:
    print(i)

3
3
1
CPU times: user 313 µs, sys: 60 µs, total: 373 µs
Wall time: 319 µs


In [12]:
%%time
print(a)

[3 3 1]
CPU times: user 246 µs, sys: 51 µs, total: 297 µs
Wall time: 254 µs


Массив чисел с плавающей точкой.

In [13]:
b = array([0., 2, 1])
b.dtype

dtype('float64')

Точно такой же массив.

In [14]:
c = array([0, 2, 1], dtype=float64)
print(c)

[0. 2. 1.]


Преобразование данных

In [15]:
print(c.dtype)
print(c.astype(int))
print(c.astype(str))

float64
[0 2 1]
['0.0' '2.0' '1.0']


Массив, значения которого вычисляются функцией. Функции передаётся массив. Так что в ней можно использовать только такие операции, которые применимы к массивам.

In [16]:
def f(i):
    print(i)
    return i ** 2

a = fromfunction(f, (5,), dtype=int64)
print(a)

[0 1 2 3 4]
[ 0  1  4  9 16]


In [17]:
a = fromfunction(f, (5,), dtype=float64)
print(a)

[0. 1. 2. 3. 4.]
[ 0.  1.  4.  9. 16.]


Массивы, заполненные нулями или единицами. Часто лучше сначала создать такой массив, а потом присваивать значения его элементам.

In [18]:
a = zeros(3)
print(a)

[0. 0. 0.]


In [19]:
b = ones(3, dtype=int64)
print(b)

[1 1 1]


Если нужно создать массив, заполненный нулями, длины другого массива, то можно использовать конструкцию

Чтобы не писать отдельно включение каждой функции, можно написать сразу:

In [20]:
import numpy as np

In [21]:
np.zeros_like(b)

array([0, 0, 0])

Функция `arange` подобна `range`. Аргументы могут быть с плавающей точкой. Следует избегать ситуаций, когда $(конец-начало)/шаг$ - целое число, потому что в этом случае включение последнего элемента зависит от ошибок округления. Лучше, чтобы конец диапазона был где-то посредине шага.

In [22]:
a = np.arange(0, 9, 2)
print(a)

[0 2 4 6 8]


In [23]:
b = np.arange(0., 9, 2)
print(b)

[0. 2. 4. 6. 8.]


Последовательности чисел с постоянным шагом можно также создавать функцией `linspace`. Начало и конец диапазона включаются; последний аргумент - число точек.

In [24]:
a = np.linspace(0, 8, 5)
print(a)

[0. 2. 4. 6. 8.]


In [25]:
a = np.linspace(0, 0.1, 5)
print(a)

[0.    0.025 0.05  0.075 0.1  ]


Массив случайных чисел (из непрерывного равномерного распределения).

In [26]:
print(np.random.random(5))

[0.97695332 0.20881406 0.79885704 0.78694779 0.82249712]


Случайные числа с нормальным (гауссовым) распределением (среднее `0`, среднеквадратичное отклонение `1`).

In [27]:
print(np.random.normal(size=5))

[ 1.19387738 -1.11803097 -0.99823572 -0.15198354 -0.12483754]


## Операции над одномерными массивами

Арифметические операции проводятся поэлементно.

In [28]:
print(a + b)

[0.    2.025 4.05  6.075 8.1  ]


In [29]:
print(a - b)

[ 0.    -1.975 -3.95  -5.925 -7.9  ]


In [30]:
print(a * b)

[0.   0.05 0.2  0.45 0.8 ]


In [31]:
print(a / (b + 1))

[0.         0.00833333 0.01       0.01071429 0.01111111]


In [32]:
print(a ** 2)

[0.       0.000625 0.0025   0.005625 0.01    ]


Когда операнды разных типов, они пpиводятся к большему типу.

In [33]:
i = np.ones(5, dtype=np.int64)
print(a + i)

[1.    1.025 1.05  1.075 1.1  ]


`numpy` содержит элементарные функции, которые тоже применяются к массивам поэлементно. Они называются универсальными функциями (`ufunc`).

In [34]:
np.sin, type(np.sin)

(<ufunc 'sin'>, numpy.ufunc)

In [35]:
print(np.sin(a))
print(np.cosh(a))

[0.         0.0249974  0.04997917 0.07492971 0.09983342]
[1.         1.00031252 1.00125026 1.00281382 1.00500417]


Один из операндов может быть скаляром, а не массивом.

In [36]:
print(a + 1)

[1.    1.025 1.05  1.075 1.1  ]


In [37]:
print(2 * a)

[0.   0.05 0.1  0.15 0.2 ]


Сравнения дают булевы массивы.

In [38]:
print(a > b)

[False False False False False]


In [39]:
print(a == b)

[ True False False False False]


In [40]:
c = a > 5
print(c)

[False False False False False]


Кванторы "существует" и "для всех".

In [41]:
np.any(c), np.all(c)

(False, False)

Модификация на месте.

In [42]:
a += 1
print(a)

[1.    1.025 1.05  1.075 1.1  ]


In [43]:
b *= 2
print(b)

[ 0.  4.  8. 12. 16.]


In [44]:
b /= a
print(b)

[ 0.          3.90243902  7.61904762 11.1627907  14.54545455]


При выполнении операций над массивами деление на 0 не возбуждает исключения, а даёт значения `np.nan` или `np.inf`.

In [45]:
np.nan + 1, np.inf + 1, np.inf * 0, 1. / np.inf

(nan, inf, nan, 0.0)

Сумма и произведение всех элементов массива; максимальный и минимальный элемент; среднее и среднеквадратичное отклонение.

In [46]:
b.sum(), b.prod(), b.max(), b.min(), b.mean(), b.std()

(37.229731886566825,
 0.0,
 14.545454545454545,
 0.0,
 7.445946377313365,
 5.1428877838280656)

In [47]:
x = np.random.normal(size=1000)
x.mean(), x.std()

(0.01511612539197477, 0.9774762318593347)

Имеются встроенные функции

In [48]:
print(np.sqrt(b))
print(np.exp(b))
print(np.log(b + 1))
print(np.sin(b))
print(np.e, np.pi)

[0.         1.97545919 2.76026224 3.34107628 3.81385036]
[1.00000000e+00 4.95230899e+01 2.03662157e+03 7.04593127e+04
 2.07496438e+06]
[0.         1.58973284 2.15397459 2.49838135 2.74376828]
[ 0.         -0.68953468  0.9725297  -0.98605188  0.91780205]
2.718281828459045 3.141592653589793


Иногда бывает нужно использовать частичные (кумулятивные) суммы. В нашем курсе такое пригодится.

In [49]:
print(b.cumsum()[::-1])

[37.22973189 22.68427734 11.52148664  3.90243902  0.        ]


Функция `sort` возвращает отсортированную копию, метод `sort` сортирует на месте.

In [50]:
print(np.sort(b))
print(b)

[ 0.          3.90243902  7.61904762 11.1627907  14.54545455]
[ 0.          3.90243902  7.61904762 11.1627907  14.54545455]


In [51]:
b.sort()
print(b)

[ 0.          3.90243902  7.61904762 11.1627907  14.54545455]


Объединение массивов "по-горизонтали" (horizontal stack).

In [52]:
a = np.array([1, 2, 3])
b = np.array([100, 200, 300])

print(np.hstack((a, b)))

[  1   2   3 100 200 300]


Объединение массивов "по-вертикали" (vertical stack).

In [53]:
print(np.vstack((a, b)))

[[  1   2   3]
 [100 200 300]]


Расщепление массива в позициях 3 и 6.

In [54]:
a = np.random.random(10)
np.hsplit(a, [3, 6])

[array([0.64501372, 0.99102171, 0.28545633]),
 array([0.6489831 , 0.95678594, 0.80428645]),
 array([0.59815893, 0.81674245, 0.44190248, 0.47429843])]

Функции `delete`, `insert` и `append` не меняют массив на месте, а возвращают новый массив, в котором удалены, вставлены в середину или добавлены в конец какие-то элементы.

In [55]:
a = np.arange(10)

In [56]:
a = np.delete(a, [5, 7])
print(a)

[0 1 2 3 4 6 8 9]


In [57]:
a = np.insert(a, 2, [0, 0])
print(a)

[0 1 0 0 2 3 4 6 8 9]


In [58]:
a = np.append(a, [1, 2, 3])
print(a)

[0 1 0 0 2 3 4 6 8 9 1 2 3]


Есть несколько способов индексации массива. Вот обычный индекс.

In [59]:
a = np.linspace(0, 1, 11)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [60]:
b = a[2]
print(b)

0.2


Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.

In [61]:
b = a[2:6]
print(b)

[0.2 0.3 0.4 0.5]


In [62]:
b[0] = -0.2
print(b)

[-0.2  0.3  0.4  0.5]


In [63]:
print(a)

[ 0.   0.1 -0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


Диапазон с шагом 2.

In [64]:
b = a[1:10:2]
print(b)

[0.1 0.3 0.5 0.7 0.9]


In [65]:
b[0] = -0.1
print(a)

[ 0.  -0.1 -0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


Массив в обратном порядке.

In [66]:
b = a[len(a):0:-1]
print(b)

[ 1.   0.9  0.8  0.7  0.6  0.5  0.4  0.3 -0.2 -0.1]


Подмассиву можно присвоить значение - массив правильного размера или скаляр.

In [67]:
a[1:10:3] = 0
print(a)

[ 0.   0.  -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Тут опять создаётся только новый заголовок, указывающий на те же данные.

In [68]:
b = a[:]
b[1] = 0.1
print(a)

[ 0.   0.1 -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Чтобы скопировать и данные массива, нужно использовать метод `copy`.

In [69]:
b = a.copy()
b[2] = 0
print(b)
print(a)

[0.  0.1 0.  0.3 0.  0.5 0.6 0.  0.8 0.9 1. ]
[ 0.   0.1 -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Можно задать список индексов.

In [70]:
print(a[[2, 3, 5]])

[-0.2  0.3  0.5]


Можно задать булев массив той же величины.

In [71]:
b = a > 0
print(b)

[False  True False  True False  True  True False  True  True  True]


In [72]:
print(a[b])

[0.1 0.3 0.5 0.6 0.8 0.9 1. ]


## 2-мерные массивы

In [73]:
a = np.array([[0.0, 1.0], [-1.0, 0.0]])
print(a)

[[ 0.  1.]
 [-1.  0.]]


In [74]:
a.ndim

2

In [75]:
a.shape

(2, 2)

In [76]:
len(a), a.size

(2, 4)

In [77]:
a[1, 0]

-1.0

Атрибуту `shape` можно присвоить новое значение - кортеж размеров по всем координатам. Получится новый заголовок массива; его данные не изменятся.

In [78]:
b = np.linspace(0, 3, 4)
print(b)

[0. 1. 2. 3.]


In [79]:
b.shape

(4,)

In [80]:
b.shape = 2, 2
print(b)

[[0. 1.]
 [2. 3.]]


Можно растянуть в одномерный массив

In [81]:
print(b.ravel())

[0. 1. 2. 3.]


Арифметические операции поэлементные

In [82]:
print(a + 1)
print(a * 2)
print(a + [0, 1])  # второе слагаемое дополняется до матрицы копированием строк
print(a + np.array([[0, 2]]).T)  # .T - транспонирование
print(a + b)

[[1. 2.]
 [0. 1.]]
[[ 0.  2.]
 [-2.  0.]]
[[ 0.  2.]
 [-1.  1.]]
[[0. 1.]
 [1. 2.]]
[[0. 2.]
 [1. 3.]]


Поэлементное и матричное (только в Python 3.5) умножение.

In [83]:
print(a * b)

[[ 0.  1.]
 [-2.  0.]]


In [84]:
print(a @ b)

[[ 2.  3.]
 [ 0. -1.]]


In [85]:
print(b @ a)

[[-1.  0.]
 [-3.  2.]]


Умножение матрицы на вектор.

In [86]:
v = np.array([1, -1], dtype=np.float64)
print(b @ v)

[-1. -1.]


In [87]:
print(v @ b)

[-2. -2.]


Если у вас Питон более ранней версии, то для работы с матрицами можно использовать класс `np.matrix`, в котором операция умножения реализуется как матричное умножение.

In [88]:
np.matrix(a) * np.matrix(b)

matrix([[ 2.,  3.],
        [ 0., -1.]])

Внешнее произведение $a_{ij}=u_i v_j$

In [89]:
u = np.linspace(1, 2, 2)
v = np.linspace(2, 4, 3)
print(u)
print(v)

[1. 2.]
[2. 3. 4.]


In [90]:
a = np.outer(u, v)
print(a)

[[2. 3. 4.]
 [4. 6. 8.]]


Двумерные массивы, зависящие только от одного индекса: $x_{ij}=u_j$, $y_{ij}=v_i$

In [91]:
x, y = np.meshgrid(u, v)
print(x)
print(y)

[[1. 2.]
 [1. 2.]
 [1. 2.]]
[[2. 2.]
 [3. 3.]
 [4. 4.]]


Единичная матрица.

In [92]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Метод `reshape` делает то же самое, что присваивание атрибуту `shape`.

In [93]:
print(I.reshape(16))

[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


In [94]:
print(I.reshape(2, 8))

[[1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]]


Строка.

In [95]:
print(I[1])

[0. 1. 0. 0.]


Цикл по строкам.

In [96]:
for row in I:
    print(row)

[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]


Столбец.

In [97]:
print(I[:, 2])

[0. 0. 1. 0.]


Подматрица.

In [98]:
print(I[0:2, 1:3])

[[0. 0.]
 [1. 0.]]


Можно построить двумерный массив из функции.

In [99]:
def f(i, j):
    print(i)
    print(j)
    return 10 * i + j

print(np.fromfunction(f, (4, 4), dtype=np.int64))

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


Транспонированная матрица.

In [100]:
print(b.T)

[[0. 2.]
 [1. 3.]]


Соединение матриц по горизонтали и по вертикали.

In [101]:
a = np.array([[0, 1], [2, 3]])
b = np.array([[4, 5, 6], [7, 8, 9]])
c = np.array([[4, 5], [6, 7], [8, 9]])
print(a)
print(b)
print(c)

[[0 1]
 [2 3]]
[[4 5 6]
 [7 8 9]]
[[4 5]
 [6 7]
 [8 9]]


In [102]:
print(np.hstack((a, b)))

[[0 1 4 5 6]
 [2 3 7 8 9]]


In [103]:
print(np.vstack((a, c)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Сумма всех элементов; суммы столбцов; суммы строк.

In [104]:
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

39
[11 13 15]
[15 24]


Аналогично работают `prod`, `max`, `min` и т.д.

In [105]:
print(b.max())
print(b.max(axis=0))
print(b.min(axis=1))

9
[7 8 9]
[4 7]


След - сумма диагональных элементов.

In [106]:
np.trace(a)

3

## Многомерные массивы
опциональный материал

In [107]:
X = np.arange(24).reshape(2, 3, 4)
print(X)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Суммирование (аналогично остальные операции)

In [108]:
# суммируем только по нулевой оси, то есть для фиксированных j и k суммируем только элементы с индексами (*, j, k)
print(X.sum(axis=0))
# суммируем сразу по двум осям, то есть для фиксированной i суммируем только элементы с индексами (i, *, *)
print(X.sum(axis=(1, 2)))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[ 66 210]


## Линейная алгебра

In [109]:
np.linalg.det(a)

-2.0

Обратная матрица.

In [110]:
a1 = np.linalg.inv(a)
print(a1)

[[-1.5  0.5]
 [ 1.   0. ]]


In [111]:
print(a @ a1)
print(a1 @ a)

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


Решение линейной системы $au=v$.

In [112]:
v = np.array([0, 1], dtype=np.float64)
print(a1 @ v)

[0.5 0. ]


In [113]:
u = np.linalg.solve(a, v)
print(u)

[0.5 0. ]


Проверим.

In [114]:
print(a @ u - v)

[0. 0.]


Собственные значения и собственные векторы: $a u_i = \lambda_i u_i$. `l` - одномерный массив собственных значений $\lambda_i$, столбцы матрицы $u$ - собственные векторы $u_i$.

In [115]:
l, u = np.linalg.eig(a)
print(l)

[-0.56155281  3.56155281]


In [116]:
print(u)

[[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


Проверим.

In [117]:
for i in range(2):
    print(a @ u[:, i] - l[i] * u[:, i])

[0.00000000e+00 1.66533454e-16]
[ 0.0000000e+00 -4.4408921e-16]


Функция `diag` от одномерного массива строит диагональную матрицу; от квадратной матрицы - возвращает одномерный массив её диагональных элементов.

In [118]:
L = np.diag(l)
print(L)
print(np.diag(L))

[[-0.56155281  0.        ]
 [ 0.          3.56155281]]
[-0.56155281  3.56155281]


Все уравнения $a u_i = \lambda_i u_i$ можно собрать в одно матричное уравнение $a u = u \Lambda$, где $\Lambda$ - диагональная матрица с собственными значениями $\lambda_i$ на диагонали.

In [119]:
print(a @ u - u @ L)

[[0.00000000e+00 0.00000000e+00]
 [1.11022302e-16 0.00000000e+00]]


Поэтому $u^{-1} a u = \Lambda$.

In [120]:
print(np.linalg.inv(u) @ a @ u)

[[-5.61552813e-01  1.47801400e-17]
 [-1.25939966e-16  3.56155281e+00]]


Найдём теперь левые собственные векторы $v_i a = \lambda_i v_i$ (собственные значения $\lambda_i$ те же самые).

In [121]:
l, v = np.linalg.eig(a.T)
print(l)
print(v)

[-0.56155281  3.56155281]
[[-0.96276969 -0.48963374]
 [ 0.27032301 -0.87192821]]


Собственные векторы нормированы на 1.

In [122]:
print(u.T @ u)
print(v.T @ v)

[[ 1.         -0.23570226]
 [-0.23570226  1.        ]]
[[1.         0.23570226]
 [0.23570226 1.        ]]


Левые и правые собственные векторы, соответствующие разным собственным значениям, ортогональны, потому что $v_i a u_j = \lambda_i v_i u_j = \lambda_j v_i u_j$.

In [123]:
print(v.T @ u)

[[ 9.71825316e-01 -7.57355847e-18]
 [-4.34446700e-17  9.71825316e-01]]


# Интегрирование

In [124]:
from scipy.integrate import quad, odeint
from scipy.special import erf

In [125]:
def f(x):
    return np.exp(-x ** 2)

Адаптивное численное интегрирование (может быть до бесконечности). `err` - оценка ошибки.

In [126]:
res, err = quad(f, 0, np.inf)
print(np.sqrt(np.pi) / 2, res, err)

0.8862269254527579 0.8862269254527579 7.101318390472462e-09


In [127]:
res, err =  quad(f, 0, 1)
print(np.sqrt(np.pi) / 2 * erf(1), res, err)

0.7468241328124269 0.7468241328124271 8.291413475940725e-15


## Сохранение в файл и чтение из файла

In [128]:
x = np.arange(0, 25, 0.5).reshape((5, 10))

# Сохраняем в файл example.txt данные x в формате с двумя точками после запятой и разделителем ';'
np.savetxt('example.txt', x, fmt='%.2f', delimiter=';')

Получится такой файл

In [129]:
!cat example.txt

0.00;0.50;1.00;1.50;2.00;2.50;3.00;3.50;4.00;4.50
5.00;5.50;6.00;6.50;7.00;7.50;8.00;8.50;9.00;9.50
10.00;10.50;11.00;11.50;12.00;12.50;13.00;13.50;14.00;14.50
15.00;15.50;16.00;16.50;17.00;17.50;18.00;18.50;19.00;19.50
20.00;20.50;21.00;21.50;22.00;22.50;23.00;23.50;24.00;24.50
